name: Set Github_Env
on:
  push:
    branches:
      - test
jobs:
  
  store-env:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: store env
        run: |
          DYNAMIC_VER="v5.0.${{ github.run_number }}"
          echo "MY_VERSION=$DYNAMIC_VER" >> $GITHUB_ENV

      - name: display env
        run: echo "Deploying version $MY_VERSION"

      - name: Production Step
        if: github.ref_name == 'main'
        run: echo "Deploying to production..."
    
